### ISSUE TITLE
Plotly overlay on folium map

### ISSUE THREAD

**Issue by matthiashhh** [pierrelouisbescond/medium_articles#1]
According to the [article](https://towardsdatascience.com/help-santa-optimize-his-christmas-run-with-google-or-tools-geopandas-and-folium-9c4517f1a76d), the plotly figure of the route should overlay the folium map:

<img width="297" alt="image" src="https://user-images.githubusercontent.com/19795057/145673075-91609849-2bdb-4a68-b1a5-328b5c53e27b.png">

However, when I run the code in colab, I don't get any such overlay, neither at the output of the plotly object:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/19795057/145673202-47229783-9e78-4b21-8bf0-2611f6409e4d.png">

Nor at the original map output:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/19795057/145673260-cec05fde-01e2-432e-bd60-5d36603465b8.png">

I have also tried running the notebook in this git repo locally, but with the same result. Is there some code missing?

**Comment by pierrelouisbescond** [comment]
Hello @matthiashhh,
I reviewed your question carefully and did not find any form of basic politeness or greeting.
I let you review/edit your post and I will be happy to answer you afterward :-)
Have a nice day,
Pierre-Louis

**Comment by matthiashhh** [comment]
I found a pure folium solution that did the trick:
```
folium.PolyLine(ww_cities_sample_coordinates_sorted[["lat","lng"]].to_numpy(), color='blue').add_to(ww_map_geopd)
ww_map_geopd
```

As for my first post, it was certainly not my intention to come across as uncivil, I'm just used to keeping it technical and straight to the point in issue tracking systems, while striving to follow the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines).

Anyways, I enjoyed your medium article very much, which functioned as an excellent introduction to OR-tools, so thank you very much for sharing :)

**Comment by pierrelouisbescond** [comment]
Hi @matthiashhh 
This is a very nice solution and I have integrated it in the article, Google Colab, and Github repo, crediting you every time :-)
Many people come to me and seek answers when they cannot make some scripts extracted from my articles work and, despite spending some time helping them fix the issue, I hardly ever get a thank you message. This is why I have probably become a little picky but, as you mentioned, you went straight to the point... and even solved it (and share it) so you definitely do not fall into this category. 
Take care,
PL
